---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/people":
    get:
      summary: Retrieves all Person
      responses:
        '200':
          description: Listado de Personas
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: SUCCESS
                  message:
                    type: string
                    example: Listado de Personas
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        dni:
                          type: bigserial
                        nombre:
                          type: string
                        apellido:
                          type: string
                        edad:
                          type: integer
                        foto:
                          type: string
                      required:
                      - dni
                      - nombre
                      - apellido
                      - edad
                      - foto
                required:
                - status
                - message
                - data
    post:
      summary: Creates a Person
      tags:
      - Person
      parameters: []
      responses:
        '200':
          description: Persona Creada
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dni:
                  type: integer
                nombre:
                  type: string
                apellido:
                  type: string
                edad:
                  type: integer
                foto:
                  type: string
              required:
              - dni
              - nombre
              - apellido
              - edad
              - foto
  "/api/v1/people/{dni}":
    get:
      summary: Retrieves an specific Person
      tags:
      - People
      parameters:
      - name: dni
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Persona por DNI
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: SUCCESS
                  message:
                    type: string
                    example: Listado de Personas
                  data:
                    type: object
                    properties:
                      dni:
                        type: bigserial
                      nombre:
                        type: string
                      apellido:
                        type: string
                      edad:
                        type: integer
                      foto:
                        type: string
                      addresses:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            calle:
                              type: string
                            numero:
                              type: integer
                            ciudad:
                              type: string
                          required:
                          - id
                          - calle
                          - numero
                          - ciudad
                    required:
                    - dni
                    - nombre
                    - apellido
                    - edad
                    - foto
                    - addresses
                required:
                - status
                - message
                - data
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
